# Generated by Django 5.1.15 on 2026-10-03 13:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('full_name', models.CharField(db_index=True, help_text='Official name as printed on passport or government ID', max_length=200, verbose_name='full name')),
                ('cnic', models.CharField(db_index=True, help_text='Pakistani CNIC or juvenile B-Form number (e.g. 35202-1234567-1)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC / B-Form must follow the standard 13-digit format: XXXXX-XXXXXXX-X', regex='^\\d{5}-\\d{7}-\\d{1}$')], verbose_name='CNIC / B-Form number')),
                ('phone_number', models.CharField(db_index=True, help_text='Primary contact number', max_length=32, verbose_name='phone / WhatsApp number')),
                ('passport_number', models.CharField(blank=True, db_index=True, help_text='International travel passport identifier (optional at pre-registration)', max_length=30, null=True, unique=True, verbose_name='passport number')),
                ('age_category', models.CharField(choices=[('ADULT', 'Adult (Age 12+)'), ('CHILD', 'Child (Age 2-11)'), ('INFANT', 'Infant (Under 2)')], db_index=True, default='ADULT', max_length=10, verbose_name='age category')),
                ('address', models.TextField(blank=True, default='', verbose_name='residential address')),
                ('emergency_contact', models.CharField(blank=True, default='', help_text='Name and phone of emergency family contact in Pakistan', max_length=100, verbose_name='emergency contact')),
                ('notes', models.TextField(blank=True, default='', help_text='Medical requirements, mobility assistance, wheelchair, dietary preferences', verbose_name='operational notes')),
                ('guardian', models.ForeignKey(blank=True, help_text='Designated primary guardian or head of family unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='travelers.traveler')),
            ],
            options={
                'verbose_name': 'traveler',
                'verbose_name_plural': 'travelers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cnic', 'full_name'], name='travelers_t_cnic_00a3b7_idx'), models.Index(fields=['age_category', 'created_at'], name='travelers_t_age_cat_7feac8_idx')],
            },
        ),
    ]
