# Generated by Django 5.1.15 on 2026-10-04 11:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('agency_name', models.CharField(db_index=True, help_text="Name of wholesale ticketing agency or distributor (e.g. Air Falcon, Gerry's)", max_length=200, verbose_name='ticketing agency / consolidator')),
                ('airline_name', models.CharField(db_index=True, help_text='Operating airline carrier (e.g. PIA, Saudia, Emirates, Fly Jinnah)', max_length=150, verbose_name='airline name')),
                ('pnr_number', models.CharField(db_index=True, help_text='Passenger Name Record alphanumeric identifier', max_length=12, validators=[django.core.validators.RegexValidator(message='PNR must be 5 to 12 uppercase alphanumeric characters.', regex='^[A-Z0-9]{5,12}$')], verbose_name='PNR booking code')),
                ('total_tickets', models.PositiveIntegerField(help_text='Total number of seats issued under this PNR record', validators=[django.core.validators.MinValueValidator(1)], verbose_name='total passenger seats')),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='issue / purchase date')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total wholesale invoice cost for all seats under this PNR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total purchase price')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='ISSUED', max_length=25, verbose_name='ticket status')),
                ('notes', models.TextField(blank=True, default='', help_text='Sectors (e.g. KHI-JED-KHI), flight numbers, baggage allowance, or booking notes', verbose_name='routing / flight notes')),
                ('created_by', models.ForeignKey(help_text='Agent or user who booked this ticket', on_delete=django.db.models.deletion.PROTECT, related_name='issued_agency_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agency ticket',
                'verbose_name_plural': 'agency tickets',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('refund_seats_count', models.PositiveIntegerField(help_text='Number of seats cancelled in this refund transaction', validators=[django.core.validators.MinValueValidator(1)], verbose_name='seats refunded')),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Gross fare snapshot for the seats being refunded', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='gross amount')),
                ('penalty_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Airline or agency cancellation penalty', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='airline penalty / deduction fine')),
                ('net_refund_amount', models.DecimalField(decimal_places=2, help_text='Net amount refunded: original_amount - penalty_fee', max_digits=12, verbose_name='net refund issued')),
                ('refund_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='refund date')),
                ('refund_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_ADJUSTMENT', 'Agency Credit Adjustment')], default='CASH', max_length=25, verbose_name='refund payment method')),
                ('reason', models.TextField(blank=True, default='', help_text='Client cancellation, flight schedule cancellation, visa issue, etc.', verbose_name='refund reason')),
                ('processed_by', models.ForeignKey(help_text='Staff or accountant who processed this refund', on_delete=django.db.models.deletion.PROTECT, related_name='processed_ticket_refunds', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Agency ticket booking being refunded', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='ticketing.agencyticket')),
            ],
            options={
                'verbose_name': 'ticket refund',
                'verbose_name_plural': 'ticket refunds',
                'ordering': ['-refund_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agencyticket',
            index=models.Index(fields=['agency_name', 'airline_name'], name='ticketing_a_agency__07c396_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyticket',
            index=models.Index(fields=['pnr_number', 'status'], name='ticketing_a_pnr_num_f2a1b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketrefund',
            constraint=models.CheckConstraint(condition=models.Q(('net_refund_amount__lte', models.F('original_amount'))), name='net_refund_lte_original'),
        ),
        migrations.AddConstraint(
            model_name='ticketrefund',
            constraint=models.CheckConstraint(condition=models.Q(('penalty_fee__gte', Decimal('0.00'))), name='penalty_fee_non_negative'),
        ),
    ]
