# Generated by Django 5.1.15 on 2026-10-03 13:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('title', models.CharField(db_index=True, help_text='e.g. 15-Day Executive Umrah Group Tour', max_length=255, verbose_name='package title')),
                ('package_code', models.CharField(db_index=True, help_text='Unique inventory tracking reference (e.g. PKG-2026-UMR-01)', max_length=50, unique=True, verbose_name='package code')),
                ('location', models.CharField(choices=[('MAKKAH', 'Makkah Mukarramah'), ('MADINAH', 'Madinah Munawwarah'), ('MAKKAH_MADINAH', 'Combined Makkah & Madinah')], default='MAKKAH_MADINAH', max_length=20, verbose_name='location / itinerary')),
                ('star_rating', models.CharField(choices=[('3_STAR', '3 Star Economy'), ('4_STAR', '4 Star Standard'), ('5_STAR', '5 Star Luxury VIP')], default='4_STAR', max_length=10, verbose_name='hotel tier')),
                ('shuttle_service', models.BooleanField(default=False, help_text='Dedicated shuttle between hotel and Haramain grounds', verbose_name='shuttle transport included')),
                ('flight_name', models.CharField(help_text='e.g. Saudia SV-738 (Lahore to Jeddah)', max_length=150, verbose_name='airline & flight code')),
                ('departure_date', models.DateField(db_index=True, verbose_name='departure date')),
                ('return_date', models.DateField(db_index=True, verbose_name='return date')),
                ('adult_price', models.DecimalField(decimal_places=2, help_text='Base price for travelers aged 12 and above', max_digits=12, verbose_name='adult base price')),
                ('child_price', models.DecimalField(decimal_places=2, help_text='Base price for children aged 2-11 with separate bed/seat', max_digits=12, verbose_name='child base price')),
                ('infant_price', models.DecimalField(decimal_places=2, help_text='Base fare for infants under 2 years', max_digits=12, verbose_name='infant base price')),
                ('capacity', models.PositiveIntegerField(default=50, help_text='Maximum quota of passenger seats for this package departure', verbose_name='total passenger quota')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active (Open for Booking)'), ('COMPLETED', 'Completed (Tour Concluded)'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=15, verbose_name='status')),
                ('description', models.TextField(blank=True, default='', verbose_name='itinerary & package details')),
            ],
            options={
                'verbose_name': 'travel package',
                'verbose_name_plural': 'travel packages',
                'ordering': ['-departure_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'departure_date'], name='packages_tr_status_082686_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackageEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('enrollment_number', models.CharField(db_index=True, help_text='System-generated dossier identifier (e.g. ENR-2026-0001)', max_length=64, unique=True, verbose_name='enrollment number')),
                ('enrolled_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='enrollment date')),
                ('base_price_applied', models.DecimalField(decimal_places=2, help_text='Snapshot of the age-tiered rate at the time of booking', max_digits=12, verbose_name='base package price applied')),
                ('extra_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Supplemental charges (room upgrades, private transport, quad to double room, etc.)', max_digits=12, verbose_name='extra services amount')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authorized price reduction', max_digits=12, verbose_name='authorized discount')),
                ('final_agreed_price', models.DecimalField(decimal_places=2, help_text='Calculated total: (base_price_applied + extra_amount) - discount', max_digits=12, verbose_name='final agreed total')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Participant'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Tour Completed')], db_index=True, default='ACTIVE', max_length=15, verbose_name='enrollment status')),
                ('special_requests', models.TextField(blank=True, default='', verbose_name='special client requests')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(help_text='Enrolled passenger or pilgrim', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='travelers.traveler')),
                ('package', models.ForeignKey(help_text='Assigned travel package itinerary', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='packages.travelpackage')),
            ],
            options={
                'verbose_name': 'package enrollment',
                'verbose_name_plural': 'package enrollments',
                'ordering': ['-enrolled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('receipt_number', models.CharField(db_index=True, help_text='Unique auto-generated receipt code (e.g. RCT-2026-0001)', max_length=64, unique=True, verbose_name='receipt voucher number')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monetary value received in transaction', max_digits=12, verbose_name='amount received')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='transaction date')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash in Office'), ('BANK_TRANSFER', 'Online Bank Transfer / Wire'), ('CHEQUE', 'Bank Cheque / Pay Order')], default='CASH', max_length=20, verbose_name='payment instrument')),
                ('reference_number', models.CharField(blank=True, help_text='Cheque number, bank deposit slip, or online IBFT reference', max_length=100, null=True, verbose_name='instrument / bank transaction reference')),
                ('notes', models.TextField(blank=True, default='', verbose_name='payment narration')),
                ('enrollment', models.ForeignKey(help_text='Target traveler enrollment contract', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='packages.packageenrollment')),
                ('recorded_by', models.ForeignKey(help_text='Staff or accountant who accepted and confirmed the funds', on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'traveler payment receipt',
                'verbose_name_plural': 'traveler payment receipts',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['payment_date', 'payment_method'], name='packages_tr_payment_310909_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='packageenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('traveler',), name='unique_active_package_per_traveler'),
        ),
    ]
