# Generated by Django 5.1.15 on 2026-10-06 09:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('bank_name', models.CharField(db_index=True, help_text='e.g. Meezan Bank, HBL, UBL, Bank Alfalah', max_length=150, verbose_name='bank name')),
                ('account_name', models.CharField(help_text='Official title registered on the account (e.g. Karwan-e-Asotvi Travels)', max_length=200, verbose_name='account title')),
                ('account_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='account number / IBAN')),
                ('branch_code', models.CharField(blank=True, default='', max_length=100, verbose_name='branch name or code')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='running ledger balance')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['bank_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='OfficePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('payment_reference', models.CharField(db_index=True, help_text='Human-readable transaction reference, e.g. KB-PAY-2026-0001', max_length=25, unique=True, verbose_name='payment reference ID')),
                ('person_name', models.CharField(db_index=True, max_length=200, verbose_name='person name / beneficiary / payer')),
                ('bank_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('account_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('account_number_snapshot', models.CharField(blank=True, default='', max_length=50)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit (Deposit / Inflow)'), ('DEBIT', 'Debit (Withdrawal / Outflow)'), ('TRANSFER', 'Transfer')], db_index=True, default='CREDIT', max_length=15, verbose_name='transaction type')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('ONLINE_TRANSFER', 'Online Transfer'), ('CHEQUE', 'Cheque'), ('DEPOSIT_SLIP', 'Bank Deposit Slip')], default='ONLINE_TRANSFER', max_length=20, verbose_name='payment mode')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='transaction amount')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='transaction date')),
                ('notes', models.TextField(blank=True, default='', verbose_name='purpose / remarks')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.bankaccount', verbose_name='bank account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Payment',
                'verbose_name_plural': 'Office Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficePaymentAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('added_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='added amount')),
                ('adjustment_date', models.DateField(default=django.utils.timezone.now, verbose_name='adjustment date')),
                ('notes', models.TextField(blank=True, default='')),
                ('office_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='finance.officepayment', verbose_name='office payment')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_adjustments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Payment Adjustment',
                'verbose_name_plural': 'Office Payment Adjustments',
                'ordering': ['-adjustment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('expense_reference', models.CharField(db_index=True, help_text='e.g. EXP-2026-0001', max_length=25, unique=True, verbose_name='expense voucher number')),
                ('person_name', models.CharField(db_index=True, max_length=200, verbose_name='spender / authorized staff')),
                ('item_name', models.CharField(help_text='e.g. Electricity Bill, Tea/Refreshment, Courier Charges', max_length=200, verbose_name='expense item / title')),
                ('category', models.CharField(choices=[('RENT', 'Office Rent'), ('UTILITIES', 'Electricity, Gas & Water'), ('SALARIES', 'Staff Salaries & Allowances'), ('REFRESHMENTS', 'Tea & Refreshments'), ('OFFICE_SUPPLIES', 'Stationery & Office Supplies'), ('MAINTENANCE', 'Repairs & Maintenance'), ('MARKETING', 'Advertising & Printing'), ('OTHER', 'Miscellaneous')], db_index=True, default='OTHER', max_length=25, verbose_name='category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='expense amount')),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='expense date')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('ONLINE_TRANSFER', 'Online Transfer'), ('CHEQUE', 'Cheque'), ('DEPOSIT_SLIP', 'Bank Deposit Slip')], default='CASH', max_length=20, verbose_name='payment channel')),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Expense',
                'verbose_name_plural': 'Office Expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date', 'category'], name='finance_off_expense_c21a04_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='officepayment',
            index=models.Index(fields=['payment_date', 'transaction_type'], name='finance_off_payment_1429db_idx'),
        ),
        migrations.AddIndex(
            model_name='officepayment',
            index=models.Index(fields=['person_name', 'payment_date'], name='finance_off_person__2f2883_idx'),
        ),
    ]
