# Generated by Django 5.1.15 on 2026-10-05 07:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('booking_reference', models.CharField(db_index=True, help_text='Human-readable booking reference, e.g. KB-HTL-2026-0001', max_length=25, unique=True, verbose_name='booking reference')),
                ('hotel_name', models.CharField(db_index=True, help_text='Name of hotel property (e.g. Pullman Zamzam, Swissotel, Dar Al Taqwa)', max_length=200, verbose_name='hotel property name')),
                ('location', models.CharField(choices=[('MAKKAH', 'Makkah'), ('MADINAH', 'Madinah'), ('OTHER', 'Other')], db_index=True, default='MAKKAH', max_length=20, verbose_name='city / location')),
                ('booking_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='booking date')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='check-in date')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='check-out date')),
                ('room_details', models.CharField(blank=True, default='', help_text='Optional room configuration (e.g. 2 Quad Rooms, 1 Double Bed)', max_length=255, verbose_name='room details / bedding')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total contracted price')),
                ('advance_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='advance / total paid')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='outstanding remaining amount')),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid')], db_index=True, default='UNPAID', max_length=15, verbose_name='payment status')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete status flag', verbose_name='is active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='operational notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL, verbose_name='booked by')),
            ],
            options={
                'verbose_name': 'Hotel Booking',
                'verbose_name_plural': 'Hotel Bookings',
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='settlement amount')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='payment date')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20, verbose_name='payment method')),
                ('receipt_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='receipt voucher number')),
                ('reference_number', models.CharField(blank=True, default='', max_length=100, verbose_name='cheque / transaction reference')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ledger notes')),
                ('hotel_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotels.hotelbooking', verbose_name='hotel booking')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'Hotel Payment',
                'verbose_name_plural': 'Hotel Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['is_active', 'payment_status'], name='hotels_hote_is_acti_0d3a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['location', 'booking_date'], name='hotels_hote_locatio_845235_idx'),
        ),
    ]
